FROM ubuntu:14.04
MAINTAINER Timo Runge

ARG ANSIBLE_VERSION
ARG PYTHON_VERSION
ARG ROLE_NAME
ARG WORKDIR

ENV ENV_ROLE_NAME=${ROLE_NAME}
ENV ENV_WORKDIR=${WORKDIR}

RUN apt-get update -y
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    libbz2-dev \
    libc6-dev \
    libgdbm-dev \
    libncursesw5-dev \
    libreadline-gplv2-dev \
    libsqlite3-dev \
    libssl-dev \
    tk-dev \
    wget
RUN apt-get clean

RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz -P /usr/local/src
RUN tar -xf /usr/local/src/Python-${PYTHON_VERSION}.tgz -C /usr/local/src
RUN cd /usr/local/src/Python-${PYTHON_VERSION} && ./configure --bindir=/usr/bin && make && make install

RUN wget https://bootstrap.pypa.io/get-pip.py -P /usr/local/src
RUN python /usr/local/src/get-pip.py

RUN pip install ansible==${ANSIBLE_VERSION}
RUN pip install ansible-lint coverage junit-xml splitter
RUN ansible --version

COPY ./ /etc/ansible/roles/${ROLE_NAME}
COPY ./docker/docker-entrypoint.sh /
COPY ./tests ${WORKDIR}

WORKDIR ${WORKDIR}

ENTRYPOINT [ "/docker-entrypoint.sh" ]
